Add devise
thasipablo/Rails_Blog pull request #9
Opened 2023-11-16 21:50 UTC by thasipablo

### Project requirements
- Remove `current_user` method in `ApplicationController`, devise will provide us with one.
- Install and setup devise.
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.
- Modify the views in devise

2023-11-16 22:27 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi Team
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![0bd223a2b156e0eaf61a713e84c3d3b7](https://user-images.githubusercontent.com/57408419/255594021-109e7375-12de-4f5b-9e29-79eefc52e35a.gif)



## To highlight :champagne: 

- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-16 22:27 UTC, joel-kalema commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] Good job adding devise, however, it could be better if `:confirmable` is enabled in the user model (user.rb file) to ask for confirmation of email as it is [required](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#:~:text=Ask%20for%20confirmation%20of%20email.). it'll be something like this:

```ruby
	devise :database_authenticatable, :registerable,
				:recoverable, :rememberable, :validatable, :confirmable
```

2023-11-16 22:27 UTC, joel-kalema commented on app/views/devise/registrations/new.html.erb
> +
- [ ] [OPTIONAL] it could be better if we add a `input` to get information about `bio` of the user 
![Capture1](https://github.com/Alibaba2023/blog_app/assets/57408419/390e22ea-5dc6-4c33-8e8c-3a49be7d0545)

2023-11-16 22:49 UTC, thasipablo commented on app/views/devise/registrations/new.html.erb
> +
Thank you @joel-kalema 
The confirmable was added to the user model

2023-11-16 23:50 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @thasipablo 

Great work on making the changes requested by a previous reviewer 👏! I really appreciate the effort you put in!  **_However, there are few things that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ `:confirmable` is enabled
- ✅ Descriptive PR and README file
- ✅ Linters are working properly

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-16 23:50 UTC, KanzaTahreem commented on db/migrate/20231116002615_add_devise_to_users.rb
> +
- [ ] Well done for enabling `:confirmable` in `User` model 👏 However, currently I'm currently encountering the following error while attempting to sign up ⚠ Since this issue was not present during the last review, I am requesting it as a required change ✨ This can be fixed by uncommenting the above. Let's ensure that the corresponding tables are present when using `:confirmable` in the user model as we need to ask for the [confirmation of the email](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#:~:text=Ask%20for%20confirmation%20of%20email.) as previous reviewer mentioned 

_Hint: After successful implementation, you will receive a link in your terminal to confirm your email_

![image](https://github.com/thasipablo/Rails_Blog/assets/106119105/47f3f217-f146-4d84-b890-4edb4fda3ad6)

2023-11-17 00:10 UTC, thasipablo commented on db/migrate/20231116002615_add_devise_to_users.rb
> +
Thank you @KanzaTahreem. I have fixed the issue

2023-11-17 00:33 UTC, Shedrack-Sunday approved these changes
Hi @thasipablo    👍 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Rails  features  ✔️  
- [x] Kudus on meeting the requirements as pointed by the  last reviewer   👏 

### Confirmed view:
![image](https://github.com/thasipablo/Rails_Blog/assets/50990925/beb537ca-3f8d-4ba8-a286-14e24944324a)

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-17 00:51 UTC, thasipablo commented
Thank you @Shedrack-Sunday

2023-11-17 00:51 UTC, merged